name = "301"
main = "src/api/index.ts"
compatibility_date = "2025-10-25"

[[d1_databases]]
binding = "DB301"
database_name = "<YOUR_DB_NAME>"
database_id = "<YOUR_D1_ID>"

[[kv_namespaces]]
binding = "KV_SESSIONS"
id = "<YOUR_KV_SESSIONS_ID>"

[[kv_namespaces]]
binding = "KV_CREDENTIALS"
id = "<YOUR_KV_CREDENTIALS_ID>"

