name: Sync Wiki

on:
  push:
    branches:
      - main
    paths:
      - 'wiki/**'

jobs:
  update-wiki:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # обязательно, иначе токен без прав

    steps:
      - name: Checkout main repo
        uses: actions/checkout@v4

      - name: Clone Wiki (auth with GITHUB_TOKEN)
        run: |
          echo "Cloning with token..."
          git clone "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.wiki.git" wiki_repo
          cd wiki_repo
          git branch -a

