name: Sync Wiki

on:
  push:
    branches:
      - main
    paths:
      - 'wiki/**'

jobs:
  update-wiki:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Clone Wiki repository
        run: |
          git clone "https://github.com/${{ github.repository }}.wiki.git" wiki_repo

      - name: Sync wiki content
        run: |
          rsync -av --delete wiki/ wiki_repo/
          cd wiki_repo
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Auto-update wiki from /wiki" || echo "No changes to commit"
          git push origin master

